### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by SA7BNT** [theopolisme/webcam-streamer#12]
Im running in at some Import error. Some one can help me out?

sa7bnt@owncloud:~$ webcam-streamer
-----------------------------------------------
--------------- webcam-streamer ---------------
-----------------------------------------------
webcam-streamer: Checking requirements...
webcam-streamer: Reading config...
Traceback (most recent call last):
  File "/usr/local/bin/webcam-streamer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/webcamstreamer/launcher.py", line 43, in main
    from .streamer.defaults import defaults
  File "/usr/local/lib/python3.5/dist-packages/webcamstreamer/streamer/__init__.py", line 24, in <module>
    from flask.ext.socketio import SocketIO, emit
ImportError: No module named 'flask.ext'
sa7bnt@owncloud:~$ 

Best
Tim

**Comment by kanokkorn** [comment]
@SA7BNT  try to change line from
```python 
from flask.ext.socketio import SocketIO, emit
```
 to
```python 
from flask_socketio import SocketIO, emit
```
Let's see if it can help.
