### ISSUE TITLE
ModuleNotFoundError: No module named 'defaults

### ISSUE THREAD

**Issue by arkangel-dev** [theopolisme/webcam-streamer#13]
# Cannot import defaults
Keeps throwing this error

```
C:\Users\Central>webcam-streamer
-----------------------------------------------
--------------- webcam-streamer ---------------
-----------------------------------------------
webcam-streamer: Checking requirements...
webcam-streamer: Reading config...
Traceback (most recent call last):
  File "c:\users\central\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\central\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Central\AppData\Local\Programs\Python\Python37-32\Scripts\webcam-streamer.exe\__main__.py", line 9, in <module>
  File "c:\users\central\appdata\local\programs\python\python37-32\lib\site-packages\webcamstreamer\launcher.py", line 38, in main
    from .streamer.defaults import defaults
  File "c:\users\central\appdata\local\programs\python\python37-32\lib\site-packages\webcamstreamer\streamer\__init__.py", line 23, in <module>
    from defaults import defaults
ModuleNotFoundError: No module named 'defaults'```

**Comment by DomicidalDesigns** [comment]
@arkangel-dev 
I believe this is due to using Python3 rather than Python2. In Python3 you can no longer do:
```python
from defaults import defaults
```
it now has to be
```python
from .defaults import defaults
```
Try installing/running with python 2.

Edit: Gunicorn is only designed for Linux so this won't work on Windows anyway.

**Comment by arkangel-dev** [comment]
Thanks.  Will check that out soon
