### ISSUE TITLE
No module named 'streamer'

### ISSUE THREAD

**Issue by escrowdis** [theopolisme/webcam-streamer#8]
```
>webcam-streamer
-----------------------------------------------
--------------- webcam-streamer ---------------
-----------------------------------------------
webcam-streamer: Checking requirements...
webcam-streamer: Reading config...
Traceback (most recent call last):
  File "C:\Users\User\django-t\django_venv\Scripts\webcam-streamer-script.py", line 11, in <module>
    load_entry_point('webcam-streamer==1.0.5', 'console_scripts', 'webcam-streamer')()
  File "C:\Users\User\django-t\django_venv\lib\site-packages\webcam_streamer-1.0.5-py3.5.egg\webcamstreamer\launcher.py", line 41, in main
    from streamer.defaults import defaults
ImportError: No module named 'streamer'
```

**Comment by trojek** [comment]
I have the same issue. Do you know how to solve it?

**Comment by escrowdis** [comment]
Not yet, wait for the solution. I'm doing another work right now.

**Comment by slivingston** [comment]
@trojek which version of Python are you using? My hypothesis is that the error occurs because of confusion from relative vs. absolute imports.  My proposed solution is to use

    from .streamer.defaults import defaults

(notice the leading `.`)

**Comment by jainraje** [comment]
any confirmed solution to overcome this error?
